name: 'Update Discord Commands'

on:
  push:
    branches: [ "main", "dragonbot", "moviebot" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Apply commands
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      run: .github/workflows/registerCommands.sh

